### ISSUE TITLE
WSLg crashes when take a screenshot with QQ

### ISSUE THREAD

**Issue by NijiharaTsubasa** [microsoft/wslg#348] opened 2021-07-03 05:33 UTC
# Environment

```none
Windows build number: 10.0.22000.51
Your Distribution version: 20.04
Your WSLg version: 1.0.24
```

# Steps to reproduce

 - Run anything in WSLg
 - Take a screenshot with QQ's Ctrl+Alt+A snipping tool
 - And everything crashes

Note that there's no problem with system's snipping tool, only QQ's one causing the problem.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

[logs.zip](https://github.com/microsoft/wslg/files/6757876/logs.zip)
[core.weston.gz](https://github.com/microsoft/wslg/files/6757877/core.weston.gz)

#  Expected behavior

Everything works fine

# Actual behavior

![QQ截图20210703132615](https://user-images.githubusercontent.com/7794838/124343993-6bb4fa00-dc02-11eb-8296-5e0d8560f6b8.png)

**Comment by hideyukn88** [comment] 2021-07-06 20:19
@NijiharaTsubasa, thanks for reporting the issue, may I confirm the QQ you used is https://im.qq.com/linuxqq/index.html ? and installed the corresponding package from https://im.qq.com/linuxqq/download.html ? thanks!

**Comment by sanjitako** [comment] 2021-07-08 11:06
Not only caused by QQ , if anything try to copy image data to clipboard then WSLg  crashes.

**Comment by NijiharaTsubasa** [comment] 2021-07-08 11:14
> @NijiharaTsubasa, thanks for reporting the issue, may I confirm the QQ you used is https://im.qq.com/linuxqq/index.html ? and installed the corresponding package from https://im.qq.com/linuxqq/download.html ? thanks!

I'm using Windows QQ to take the snapshot

**Comment by hideyukn88** [comment] 2021-07-19 21:23
@NijiharaTsubasa and @sanjitako, would you please update WSLg to version 1.0.26 at https://github.com/microsoft/wslg/releases/tag/v1.0.26, and send us dump files at /mnt/wslg/dumps? thanks!

**Comment by NijiharaTsubasa** [comment] 2021-08-07 05:16
> @NijiharaTsubasa and @sanjitako, would you please update WSLg to version 1.0.26 at https://github.com/microsoft/wslg/releases/tag/v1.0.26, and send us dump files at /mnt/wslg/dumps? thanks!

[weston.log](https://github.com/microsoft/wslg/files/6948615/weston.log)
[core.weston.gz](https://github.com/microsoft/wslg/files/6948616/core.weston.gz)

Sorry for late response.

**Comment by richardlawley** [comment] 2021-10-20 08:08
```none
Windows build number: 10.0.22000.258
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

I've been experiencing a related version of this problem.  I'm not actually using WSLg, it's just running as it was installed as part of the Windows 11 upgrade.

When I take a screenshot with [Greenshot](https://getgreenshot.org/) (1.2.10.6) and copy it to the clipboard, WSLg appears to die and get restarted.  This shows in process explorer as mstsc processes starting and stopping every second or so:

![image](https://user-images.githubusercontent.com/1608083/138050515-712c77b4-d6a4-40dc-ab81-9da2d8aba41a.png)

This also causes system tray icons to flash once a second, and sometimes grabs focus.  Clearing the clipboard (or copying some text to it) makes the problem stop. 

Dump: [core.zip](https://github.com/microsoft/wslg/files/7379212/core.zip)
Log Snippet: [weston-log-snippet.txt](https://github.com/microsoft/wslg/files/7379214/weston-log-snippet.txt) (this sequence of logs repeats with each process crash)
 
Additional comments:
* Cannot reproduce by copying from Snipping Tool, Paint, paint.net
* Not every copy from Greenshot causes the problem, but repeatedly copying the same image from the editor has always caused the issue within 2 or 3 copies
* With docker desktop running, I have 3 WSLg hosts, copying an image from greenshot doesn't always affect all of them - repeatedly copying the same image might affect another one.  I can easily get all 3 hosts affected.

**Comment by liyafe1997** [comment] 2022-02-06 22:38
I have this issue too, seems the clipboard sharing feature crashes mstsc.exe when QQ screenshot or some other tools copy images into the clipboard. But Win+Shift+S works fine.

**Comment by hideyukn88** [comment] 2022-04-12 21:37
@richardlawley, @liyafe1997, this issue should be fixed by newer release of WSLg from aka.ms/wslstorepage, please update, thanks!

**Closed by hideyukn88** 2022-04-12 21:37 UTC
Labels: bug, clipboard-integration
