### ISSUE TITLE
Poor Performance Running Unigine Valley

### ISSUE THREAD

**Issue by blitzcaster** [microsoft/wslg#733] opened 2022-05-07 04:37 UTC
# Environment

```none
Windows build number: 10.0.22000.0
Your Distribution version: Ubuntu 22.04
Your WSLg version: 1.0.26
```

### glxinfo
```none
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Microsoft Corporation (0xffffffff)
    Device: D3D12 (NVIDIA GeForce RTX 2080 SUPER) (0xffffffff)
    Version: 22.2.0
    Accelerated: yes
    Video memory: 24357MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.2
    Max compat profile version: 4.2
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: D3D12 (NVIDIA GeForce RTX 2080 SUPER)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 22.2.0-devel (git-cfec9a5 2022-05-06 jammy-oibaf-ppa)
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

# Steps to reproduce

Download Unigine Valley and run it on Ubuntu 22.04. Optionally also run Unigine Heaven to compare.

#  Expected behavior

### Unigine Heaven runs fine as in screenshot:
![Heaven Result](https://user-images.githubusercontent.com/29270388/167238265-3a6a3a8a-2bf2-4f83-bd98-16fba5815b34.png)

# Actual behavior

### Unigine Valley have very poor performance:
![Valley Result](https://user-images.githubusercontent.com/29270388/167238301-cd38b262-f1dc-4221-accc-e1aed110b6f1.png)

**Comment by elsaco** [comment] 2022-05-09 01:38
@blitzcaster running Heaven on a lesser RTX (3060 Ti) and with all dependencies satisfied it works on WSLg and Ubuntu-22.04. Sample benchmark run:

![unigine_heaven_benchmarking](https://user-images.githubusercontent.com/3933920/167326064-986438a3-9a35-4bb0-9497-c3dd66286511.png)

```
---- Render ----
GLRender::GLRender(): Unknown NVidia GPU
OpenGL vendor:   Microsoft Corporation
OpenGL renderer: D3D12 (NVIDIA GeForce RTX 3060 Ti)
OpenGL version:  3.3 (Core Profile) Mesa 22.0.1
OpenGL flags:    Core Profile
Found required GL_ARB_map_buffer_range
Found required GL_ARB_vertex_array_object
Found required GL_ARB_draw_instanced
Found required GL_ARB_draw_elements_base_vertex
Found required GL_ARB_transform_feedback
Found required GL_ARB_half_float_vertex
Found required GL_ARB_half_float_pixel
Found required GL_ARB_framebuffer_object
Found required GL_ARB_texture_multisample
Found required GL_ARB_uniform_buffer_object
Found required GL_ARB_geometry_shader4
Found optional GL_ARB_blend_func_extended
Found optional GL_ARB_tessellation_shader
Found optional GL_ARB_shader_bit_encoding
Found optional GL_ARB_sample_shading
Found optional GL_ARB_compute_shader
Found optional GL_ARB_gpu_shader5
Found optional GL_EXT_texture_compression_s3tc
Found optional GL_ARB_texture_compression_rgtc
Shading language:        3.30
Maximum texture size:    16384
Maximum texture units:   192
Maximum texture renders: 8
```

**Comment by blitzcaster** [comment] 2022-05-09 03:03
@elsaco Heaven is okay, can you test Valley?

**Comment by elsaco** [comment] 2022-05-09 03:30
![unigine_valley](https://user-images.githubusercontent.com/3933920/167335898-0f7401b2-dfbb-4a11-8784-da88fb1d4161.png)

**Comment by blitzcaster** [comment] 2022-05-09 03:47
> FPS is lower compared to Heaven.

Ok, it can be replicated on other system then, thank you.

**Comment by elsaco** [comment] 2022-05-10 01:42
![valley_benchmark](https://user-images.githubusercontent.com/3933920/167525570-89ddc1fe-255f-40a8-b55b-fedc96eab0d4.png)


![heaven_benchmark](https://user-images.githubusercontent.com/3933920/167525585-288fe589-60fb-4cfd-9597-0be1d7b636f2.png)

**Comment by WSLUser** [comment] 2022-06-30 16:21
Dupe of https://github.com/microsoft/wslg/discussions/146 but great screenshots that help more in seeing the FPS drop. Existing linked upstream issue exists. Suggest upvoting it for priority.

**Comment by felipebutcher** [comment] 2022-07-06 02:57
Happening here too. It's not using the 3060 on my laptop. It shows it's using the intel GPU instead.

**Comment by tiagoshibata** [comment] 2022-07-08 21:41
This should be fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/17435 . I get a much better score with that fix, and an improvement of 2.4 FPS -> 19.7 FPS

![comparison](https://user-images.githubusercontent.com/5521887/178073792-5f3f5543-0dc5-4c6d-9619-ab090b2fa505.png)

Let us know if you're still having any issues after this merge request!

**Closed** 2022-07-08 21:41 UTC
Labels: bug

**Comment by WSLUser** [comment] 2022-07-08 22:24
Much better but hope more optimizations can get it to 60 fps

**Comment by blitzcaster** [comment] 2022-10-18 07:17
> Much better but hope more optimizations can get it to 60 fps

Not meaning to bump, but he's likely running on a different GPU from my previous test. I've just retested it today and can confirm it's running much better now, thank you for the fix.

## New result
![Valley screenshot after fix](https://user-images.githubusercontent.com/29270388/196362068-ed219309-9c20-476f-b488-c0c3a1f0e2db.png)
