### ISSUE TITLE
Unigine Heaven crashes

### ISSUE THREAD

**Issue by teepean** [microsoft/wslg#34] opened 2021-04-22 07:39 UTC
# Environment

```none
Windows build number: 10.0.21364.1
Your Distribution version: Ubuntu 21.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce
Install Unigine Heaven 4.0 and run it. 

https://benchmark.unigine.com/heaven

**WSL logs**: 
[wslglogs.zip](https://github.com/microsoft/wslg/files/6356467/wslglogs.zip)

* Attach WSLg logs from  `/mnt/wslg`

[wslg_logs.zip](https://github.com/microsoft/wslg/files/6356429/wslg_logs.zip)

#  Expected behavior

The benchmark starts and runs.

# Actual behavior

The program crashes and reports: 

`Received signal SIGSEGV, invalid memory reference`

Selecting  the lowest quality settings and resolution (windowed) enables Heaven to run occasionally. Sometimes it too crashes with SIGSEGV.

`Loading "/home/user/.Heaven/heaven_4.0.cfg"...
Loading "libGPUMonitor_x64.so"...
Loading "libGL.so.1"...
Loading "libopenal.so.1"...
Set 640x360 windowed video mode
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
Set 1.00 gamma value
Unigine engine http://unigine.com/
Binary: Linux 64bit GCC 4.4.5 Release Feb 13 2013 r11284
Features: OpenGL OpenAL XPad360 Joystick Flash Editor
App path:  /mnt/c/Users/tnatk/Downloads/Unigine_Heaven-4.0/bin/
Data path: /mnt/c/Users/tnatk/Downloads/Unigine_Heaven-4.0/data/
Save path: /home/user/.Heaven/

---- System ----
System: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
CPU: AMD Ryzen 9 3900X 12-Core Processor             3792MHz MMX+ SSE SSE2 SSE3 SSSE3 SSE41 SSE42 SSE4A AVX HTT x24
GPU: Unknown GPU x1
System memory: 64272 MB
Video memory:  256 MB
Sync threads:  23
Async threads: 24

---- MathLib ----
Set SSE2 simd processor

---- Sound ----
Renderer: OpenAL Soft
OpenAL vendor:   OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version:  1.1 ALSOFT 1.19.1
Found AL_EXT_LINEAR_DISTANCE
Found AL_EXT_OFFSET
Found ALC_EXT_EFX
Found EFX Filter
Found EFX Reverb
Found EAX Reverb
Found QUAD16 format
Found 51CHN16 format
Found 61CHN16 format
Found 71CHN16 format
Maximum sources:         256
Maximum effect slots:    16
Maximum auxiliary sends: 2

---- Render ----
GLRender::GLRender(): Unknown NVidia GPU
OpenGL vendor:   Microsoft Corporation
OpenGL renderer: D3D12 (NVIDIA GeForce RTX 3070)
OpenGL version:  3.3 (Core Profile) Mesa 21.0.1
OpenGL flags:    Core Profile
Found required GL_ARB_map_buffer_range
Found required GL_ARB_vertex_array_object
Found required GL_ARB_draw_instanced
Found required GL_ARB_draw_elements_base_vertex
Found required GL_ARB_transform_feedback
Found required GL_ARB_half_float_vertex
Found required GL_ARB_half_float_pixel
Found required GL_ARB_framebuffer_object
Found required GL_ARB_texture_multisample
Found required GL_ARB_uniform_buffer_object
Found required GL_ARB_geometry_shader4
Found optional GL_ARB_blend_func_extended
Found optional GL_ARB_shader_bit_encoding
Found optional GL_EXT_texture_compression_s3tc
Found optional GL_ARB_texture_compression_rgtc
Shading language:        3.30
Maximum texture size:    16384
Maximum texture units:   160
Maximum texture renders: 8

---- Physics ----
Physics: Multi-threaded

---- PathFind ----
PathFind: Multi-threaded

GPUMonitorPlugin::init(): can't initialize GPUMonitor
EnginePlugins::init(): can't initialize "GPUMonitor" plugin
---- Interpreter ----
Version: 2.52`

**Comment by jenatali** [comment] 2021-04-22 21:59
I can reproduce this with OpenGLOn12 on Windows as well. After a (very) short investigation, it looks like our shader compiler outputs something that D3D refuses to validate.

We already have https://gitlab.freedesktop.org/mesa/mesa/-/issues/3831 tracking this from the Windows side. I strongly suspect a fix there will fix WSLg as well. Therefore, I'm closing this in favor of tracking the Mesa issue instead.

**Closed by jenatali** 2021-04-22 21:59 UTC
Labels: bug

**Comment by microhobby** [comment] 2021-04-26 00:23
@jenatali should we care about the message:

````
NVD3D10: CPU cyclestats are disabled on client virtualization
NVD3D10: CPU cyclestats are disabled on client virtualization
```

I also have this report on logs, for example using glmark2, and I don't know if that is expected. 

Another question, taking advantage, using glmark2 I have a peak of GPU usage on Task Manager, but only 1 to 2% usage after that (it seems to me that is being rendered by software)

![image](https://user-images.githubusercontent.com/2633321/116014553-368d9980-a60c-11eb-911f-b5de274ab11f.png)

**Comment by jenatali** [comment] 2021-04-26 05:19
@microhobby, the "NVD3D10" log messages come from NVIDIA's usermode graphics driver. If you see those, you know you're using hardware acceleration with an NVIDIA GPU.

As for low utilization, it's possible that it's software rendering, but more likely is just small bursts of hardware rendering with lots of CPU overhead. As was called out in the architecture blog, the WSL infrastructure for hardware acceleration isn't fully efficient yet.
