### ISSUE TITLE
WSL2 Ubuntu GUI apps are not showing up in the Windows 11 Start Menu

### ISSUE THREAD

**Issue by VictorPLopes** [microsoft/wslg#823] opened 2022-09-05 16:04 UTC
### Windows build number:

10.0.22622.0

### Your Distribution version:

Ubuntu Preview 22.10

### Your WSL versions:

WSL version: 0.66.2.0
Kernel version: 5.15.57.1
WSLg version: 1.0.42
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.590

### Steps to reproduce:

1. Enable/Download WSL
2. Download Ubuntu or Ubuntu Preview, either from the command line or the Microsoft Store
3. Install any GUI app
4. Open the Start Menu

### WSL logs:

[pulseaudio.log](https://github.com/microsoft/wslg/files/9491090/pulseaudio.log)
[stderr.log](https://github.com/microsoft/wslg/files/9491091/stderr.log)
[weston.log](https://github.com/microsoft/wslg/files/9491092/weston.log)

### Expected behavior:

The installed GUI apps should have a shortcut on the Start Menu, under the Ubuntu-Preview folder.

### Actual behavior:

The shortcuts for the GUI apps are not created in the Start Menu. Neither is the Ubuntu or Ubuntu-Preview folder in "%appdata%\Microsoft\Windows\Start Menu\Programs\". The .desktop files for the apps are generated just fine. This issue happens both with Ubuntu and Ubuntu Preview.

**Comment by adrianghc** [comment] 2022-09-07 11:24
I have the same issue, it started very recently. Uninstalling the WSL Preview from the Store and using WSL from the Windows feature + Windows Update instead fixed it, so I suppose there might be a bug with the newest WSL version from the Store.

**Comment by VictorPLopes** [comment] 2022-09-07 11:28
> I have the same issue, it started very recently. Uninstalling the WSL Preview from the Store and using WSL from the Windows feature + Windows Update instead fixed it, so I suppose there might be a bug with the newest WSL version from the Store.

Hmm, interesting. Do you know if I'll lose my distro and its files if I do what you suggested?

**Comment by adrianghc** [comment] 2022-09-07 11:54
> > I have the same issue, it started very recently. Uninstalling the WSL Preview from the Store and using WSL from the Windows feature + Windows Update instead fixed it, so I suppose there might be a bug with the newest WSL version from the Store.
> 
> Hmm, interesting. Do you know if I'll lose my distro and its files if I do what you suggested?

You shouldn't lose anything, as that will only uninstall the WSL app package and keep the distro package. However, if you're worried about that, you could copy over the ext4.vhdx to another folder during the process and move it back afterwards (or make a copy but if you're like me, that's a 180 GB file 😅).

**Comment by hideyukn88** [comment] 2022-09-07 17:09
@VictorPLopes, thanks for reporting the issue, this is known regression fixed by below PR, it will be fixed in next release, thanks!

https://github.com/microsoft/weston-mirror/pull/104

**Comment by VictorPLopes** [comment] 2022-09-07 17:46
> > > I have the same issue, it started very recently. Uninstalling the WSL Preview from the Store and using WSL from the Windows feature + Windows Update instead fixed it, so I suppose there might be a bug with the newest WSL version from the Store.
> > 
> > 
> > Hmm, interesting. Do you know if I'll lose my distro and its files if I do what you suggested?
> 
> You shouldn't lose anything, as that will only uninstall the WSL app package and keep the distro package. However, if you're worried about that, you could move over the ext4.vhdx to another folder during the process and move it back afterwards (or make a copy but if you're like me, that's a 180 GB file 😅).

Alright, thank you! Although, since hideyukn88 confirmed it to be a known issue I'll just wait for the next release.

**Comment by VictorPLopes** [comment] 2022-09-07 17:47
> @VictorPLopes, thanks for reporting the issue, this is known regression fixed by below PR, it will be fixed in next release, thanks!
> 
> [microsoft/weston-mirror#104](https://github.com/microsoft/weston-mirror/pull/104)

I see, thanks for informing me!

**Comment by zodiia** [comment] 2022-09-12 18:19
> @VictorPLopes, thanks for reporting the issue, this is known regression fixed by below PR, it will be fixed in next release, thanks!
> 
> [microsoft/weston-mirror#104](https://github.com/microsoft/weston-mirror/pull/104)

Any ETA for the new release? This currently is a huge blocker since I cannot use any graphical apps in my freshly installed WSL, and the Windows Store doesn't allow me to install previous versions of the WSL package.

**Comment by adrianghc** [comment] 2022-09-12 18:23
> > @VictorPLopes, thanks for reporting the issue, this is known regression fixed by below PR, it will be fixed in next release, thanks!
> > [microsoft/weston-mirror#104](https://github.com/microsoft/weston-mirror/pull/104)
> 
> Any ETA for the new release? This currently is a huge blocker since I cannot use any graphical apps in my freshly installed WSL, and the Windows Store doesn't allow me to install previous versions of the WSL package.

The WSL package from Windows Update works fine, you could use that temporarily. See the discussion above.

**Comment by Biswa96** [comment] 2022-09-13 09:28
You can use the WSL Preview packages from here https://github.com/microsoft/WSL/releases. Uninstall the current WSL Preview package with `Remove-AppxPackage` command in Powershell and install the msixbundle from that link with `Add-AppxPackage` command.

**Comment by gradius-v** [comment] 2022-09-13 14:53
> > > > @VictorPLopes, thanks for reporting the issue, this is known regression fixed by below PR, it will be fixed in next release, thanks!
> > > > [microsoft/weston-mirror#104](https://github.com/microsoft/weston-mirror/pull/104)
> > > 
> > > 
> > > Any ETA for the new release? This currently is a huge blocker since I cannot use any graphical apps in my freshly installed WSL, and the Windows Store doesn't allow me to install previous versions of the WSL package.
> > 
> > 
> > The WSL package from Windows Update works fine, you could use that temporarily. See the discussion above.
> 
> I cannot use it since my computer is on the Windows Insiders Program and doesn't let met download the normal WSL package (which should never be a reason for not being able to downgrade but apparently it is)

Uninstall the store version and then install via `wsl --install --inbox`

**Comment by jarrard** [comment] 2022-09-27 09:53
I have this issue but nothing I've tried fixes it.  Also wsl --install --inbox does nothing except print out the help text.

**Comment by jarrard** [comment] 2022-09-27 09:58
no luck here.

**Comment by VenelinU** [comment] 2022-10-05 18:31
I got the same problem. I have managed to create the shortcuts manually.
Create the shortcut here:
C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Ubuntu(distro name)
VLC.lnk
C:\Windows\System32\wsl.exe ~ -d Ubuntu /usr/bin/vlc

It is working like a charm :-)

**Comment by hideyukn88** [comment] 2022-10-12 23:43
Hi all, WSL 0.70.0 is just released, and this should address this issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

**Closed by hideyukn88** 2022-10-12 23:43 UTC
Labels: bug, fixinbound, start-menu-integration

**Comment by VictorPLopes** [comment] 2022-10-13 12:32
> Hi all, WSL 0.70.0 is just released, and this should address this issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

It's working fine now, thank you!
