### ISSUE TITLE
Copy/paste to a WSL2 Linux GUI app

### ISSUE THREAD

**Issue by guitargz** [microsoft/wslg#196] opened 2021-05-14 09:10 UTC
### Windows Build Number

Microsoft Windows [Version 10.0.21376.1]

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Kernel Version

5.10.16

### Distro Version

Ubuntu 20.04

### Other Software

Firefox 88

### Repro Steps

1. Copy text from a Windows app
2. Paste text into a Linux GUI app in WSL2 (e.g., Firefox 88 address bar)

### Expected Behavior

Should paste from Windows into Linux.

### Actual Behavior

Randomly does not paste from Windows into Linux ("randomly" meaning sometimes it does work). The "Paste" option shows in the context menu in Linux, but imports nothing.
Inside the Linux app (or from Linux app to Windows app) copy/paste still continues working fine.

**Comment by hideyukn88** [comment] 2021-05-14 17:01
@guitargz , thanks for reporting, this sounds dup to https://github.com/microsoft/wslg/issues/15, please share weston.log from /mnt/wslg, captured right after issue occurred, thanks!

**Comment by guitargz** [comment] 2021-05-14 17:41
19:31:25 is when the issue occurred.  
[weston.log](https://github.com/microsoft/wslg/files/6480365/weston.log)

The clipboard settings are like this 
![image](https://user-images.githubusercontent.com/76868331/118308549-5f5acd80-b4ec-11eb-8514-8ebf252d7cce.png)

**Comment by hideyukn88** [comment] 2021-05-14 18:12
@guitargz , thanks for sharing weston.log and clipboard settings. Based on that (especially below), this issues is covered by #15. Thanks!

[19:32:15.540] RDP clipboard_data_source_send (0x7f6ab0000b80) specified format (text/plain;charset=utf-8.0.0) is not supported by client

**Comment by guitargz** [comment] 2021-05-14 18:29
Ok, I will follow that issue then, thank you.
Do I understand correctly there is no fix for this yet?
Thanks!

**Comment by hideyukn88** [comment] 2021-05-14 18:34
Correct, I'm actively investigating the issue, but just can't reproduce locally. The issue is, when WSLg asks clipboard data from Windows side, Windows side returns error to WSLg on that request, thus I'm collecting more information if there is any uniqueness/difference in Windows settings. thanks!

**Comment by spronovo** [comment] 2021-05-22 02:53
Resolving as a duplicate of #15 per Hideyuki's investigation.

**Closed by spronovo** 2021-05-22 02:53 UTC
Labels: bug, duplicate
