### ISSUE TITLE
After most recent WSL update, WSL won't start

### ISSUE THREAD

**Issue by hajekj** [microsoft/wslg#33] opened 2021-04-22 07:29 UTC
# Environment

```none
Windows build number: 10.0.21364.0
Your Distribution version: Ubuntu 18.04
Your WSLg version: 1.0.17.1
WSL Update Version: 5.10.16
```

# Steps to reproduce

1. Update WSL to support WSLg
2. Run the distro

**WSL logs**: 

[wsl.zip](https://github.com/microsoft/wslg/files/6356342/wsl.zip)

#  Expected behavior

WSL should start

# Actual behavior

WSL fails to start with:
```none
The parameter is incorrect.

[process exited with code 4294967295]
```

The solutions is to disable WSLg as per: https://github.com/microsoft/WSL/issues/6839 by disabling it in `.wslconfig` file via
```none
[wsl2]
guiapplications=false
```

**Comment by hideyukn88** [comment] 2021-04-22 23:13
@hajekj , thanks for reporting this and providing wsl.etl, according to the log, your CPU only support 36bits physical address. We are working on the fix to support this type of CPU.

"Virtual machine 'Virtual Machine' cannot be started. The upper MMIO region (0x00000012001ff000) is above the supported physical address range. Make sure that the upper MMIO region is below 0x0000001000000000."

**Comment by PastorGL** [comment] 2021-04-23 01:24
@hideyukn88 does '36bits physical address' mean that Sandy/Ivy Bridge Intel CPUs are not supported this time? Which is the lowest supported, Haswell (39-bit) or Skylake (46-bit)?

**Comment by github348** [comment] 2021-04-23 08:28
if it is  a cpu issue then why adding guiapplications=false in .wslconfig fixes it?

**Comment by hajekj** [comment] 2021-04-23 08:40
@github348 I suppose that is due to the WSLg distribution running side-by-side as per https://github.com/microsoft/wslg/blob/5e9419849c89863ad36753e7c1707f20f9e0d0cd/README.md#wslg-system-distro.

**Comment by github348** [comment] 2021-04-23 09:26
@hajekj that is not the case the system distro runs in the same vm as wsl 2

**Comment by github348** [comment] 2021-04-23 09:27
"All user and system distros for a particular Windows user run within the same WSL virtual machine against a single instance of the Linux kernel. Different Windows users on a PC have their own VM

**Comment by hideyukn88** [comment] 2021-04-23 14:06
Correct, system distro runs at same VM as user distro, In WSL, all distro run on same VM. You can check with "hcsdiag list" command to see which VM host WSL instance.

And the reason this only happen with GUI support is because, in order to make efficient graphics data transfer between host, it allocate larger cache in MMIO space. This doesn't happen without WSLg enabled.

We are working on fix this, thanks for reporting this issue.

**Comment by jpchow26** [comment] 2021-04-23 23:28
> @hideyukn88 does '36bits physical address' mean that Sandy/Ivy Bridge Intel CPUs are not supported this time? Which is the lowest supported, Haswell (39-bit) or Skylake (46-bit)?

Makes sense. I hit this issue on my i5-2500k which is Sandy Bridge

**Comment by MaximoTrinidad** [comment] 2021-04-23 23:43
I'm in the same boat!

Everything was working after installing the WSLg Preview before updating to Windows Insider update build 21364.
It seems like I lost everything I invested in rebuilding my WSL2 Ubuntu 18.04 before this crash. 

This is sad that there's a good chance that Windows Insider will impact WSL installations.

**Comment by ABQJuan** [comment] 2021-04-25 14:45
Same

**Comment by keitarobr** [comment] 2021-04-25 17:38
Same here - i7-3770 processor.

**Comment by Matrix2048** [comment] 2021-04-27 23:34
My issue is that it thinks I didn't turn on the Virtual Machine Platform feature even though I clearly did! Am I the only one facing this?

**Comment by UnknownFX02** [comment] 2021-04-28 02:42
@hajekj how i can get wsl.etl

**Comment by kinglionsz** [comment] 2021-04-28 05:09
I'm in the same boat!

Everything was working after installing the WSLg Preview(5.10.16.3) before updating to Windows Insider update build 21364.

so pls rollback  to 21359, all are ok.

![wsl2-5 10 16 3-@win10-21359-gui-ok](https://user-images.githubusercontent.com/51827261/116349551-d6247500-a822-11eb-92cd-86adc05f19e6.png)

**Comment by kinglionsz** [comment] 2021-04-28 05:09
> I'm in the same boat!
> 
> Everything was working after installing the WSLg Preview before updating to Windows Insider update build 21364.
> It seems like I lost everything I invested in rebuilding my WSL2 Ubuntu 18.04 before this crash.
> 
> This is sad that there's a good chance that Windows Insider will impact WSL installations.

tks.

**Comment by kinglionsz** [comment] 2021-04-28 06:38
> @hajekj how i can get my wsl.etl

pls refer to：

https://github.com/Microsoft/WSL/blob/master/CONTRIBUTING.md#networking-issues

Networking issues
If the issue is about networking, run networking.bat in an administrative command prompt:

$ git clone https://github.com/microsoft/WSL --depth=1 %tmp%\WSL
$ cd %tmp%\WSL\diagnostics
$ networking.bat
Once the script execution is completed, include both its output and the generated log file, wsl.etl on the issue.

https://github.com/Microsoft/WSL/blob/master/diagnostics/networking.bat

**Comment by jpchow26** [comment] 2021-04-29 18:19
Issue will be closed soon see https://github.com/microsoft/WSL/issues/6839#issuecomment-829440007

**Comment by kinglionsz** [comment] 2021-05-05 22:23
> # Environment
> ```
> Windows build number: 10.0.21364.0
> Your Distribution version: Ubuntu 18.04
> Your WSLg version: 1.0.17.1
> WSL Update Version: 5.10.16
> ```
> 
> # Steps to reproduce
> 1. Update WSL to support WSLg
> 2. Run the distro
> 
> **WSL logs**:
> 
> [wsl.zip](https://github.com/microsoft/wslg/files/6356342/wsl.zip)
> 
> # Expected behavior
> WSL should start
> 
> # Actual behavior
> WSL fails to start with:
> 
> ```
> The parameter is incorrect.
> 
> [process exited with code 4294967295]
> ```
> 
> The solutions is to disable WSLg as per: [microsoft/WSL#6839](https://github.com/microsoft/WSL/issues/6839) by disabling it in `.wslconfig` file via
> 
> ```
> [wsl2]
> guiapplications=false
> ```

Update to  21370.co_release210424-1611.

WSL fails to start with:

The parameter is incorrect.

[process exited with code 4294967295]
The solutions is to disable WSLg as per: microsoft/WSL#6839 by disabling it in .wslconfig file via

[wsl2]
guiapplications=false

**Comment by kinglionsz** [comment] 2021-05-05 22:36
> Issue will be closed soon see [microsoft/WSL#6839 (comment)](https://github.com/microsoft/WSL/issues/6839#issuecomment-829440007)

Update to 21370.co_release210424-1611.

WSL fails to start with:

```
The parameter is incorrect.

[process exited with code 4294967295]
```
The solutions is to disable WSLg as per: microsoft/WSL#6839 by disabling it in .wslconfig file via

[wsl2]
guiapplications=false

**Comment by ABQJuan** [comment] 2021-05-05 22:55
I've tried the new update (21370) and I still have the same issue.

**Comment by benhillis** [comment] 2021-05-05 23:02
@ABQJuan - The fix is not in 21370, but will be in this week's Insider Dev build (21376).

**Comment by fvogliotti** [comment] 2021-05-06 01:07
AWESOME!!! Thanks!!

**Comment by kinglionsz** [comment] 2021-05-06 01:19
> @ABQJuan - The fix is not in 21370, but will be in this week's Insider Dev build (21376).

Thank you so much👍👏

**Comment by bpulliam** [comment] 2021-05-06 15:21
Build 21376 releases today.  We encourage you to turn GUI applications back on, as that should now be fixed (you can remove guiapplications=false from .wslconfig).

**Closed by bpulliam** 2021-05-06 15:21 UTC
Labels: bug, fixinbound

**Comment by kinglionsz** [comment] 2021-05-06 22:28
tks so much. I'll have a try now. @[bpulliam ](https://github.com/bpulliam)

**Comment by kinglionsz** [comment] 2021-05-07 04:47
Thank you  so much !

It's ok now.

`
```
PS C:\WINDOWS\system32> wsl --status;cmd /c ver
Default Distribution: Kali-linux
Default Version: 2

Windows Subsystem for Linux was last updated on 2021/4/17
WSL automatic updates are on.

Kernel version: 5.10.16

Microsoft Windows [Version 10.0.21376.1]`
```

`
```
PS C:\scripts> wsl -e uname -a
Linux DESKTOP-J925CM6 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
'
```

![wsl-ok-21376-Screenshot 2021-05-07 123233](https://user-images.githubusercontent.com/51827261/117399037-2e016100-af32-11eb-8914-31537e2480ab.png)

**Comment by kinglionsz** [comment] 2021-05-07 10:19
Confirmed, GUI is now working Update 21376. Tks.

![wsl-ok-21376-Screenshot 2021-05-07 123233](https://user-images.githubusercontent.com/51827261/117435681-b3036f00-af60-11eb-8fda-92593a079ebf.png)

**Comment by fvogliotti** [comment] 2021-05-07 14:34
Awesomeeeeee!! Thanks!!

**Comment by Meltrust** [comment] 2021-05-10 05:28
> 
> 
> Confirmed, GUI is now working Update 21376. Tks.
> 
> ![wsl-ok-21376-Screenshot 2021-05-07 123233](https://user-images.githubusercontent.com/51827261/117436039-1c837d80-af61-11eb-9fee-cd95b7be81f2.png)

How did you get that beautiful GUI? And the dark file explorer?

**Comment by eternalphane** [comment] 2021-05-10 09:39
@Meltrust seems to be this one: [MyDockFinder](https://github.com/mydockfinder/mydockfinder)

**Comment by kinglionsz** [comment] 2021-05-11 09:56
> > Confirmed, GUI is now working Update 21376. Tks.
> 
> How did you get that beautiful GUI? And the dark file explorer?

@Meltrust

1, GUI https://www.mydockfinder.com/  
2, dark file explorer : Kali Linux Thunar 

enjoy it😊

**Comment by konstantinosbotonakis** [comment] 2021-05-19 12:07
For me the solution was to create the .wslconfig file using notepad into c:/users/your_user_name/ folder.

Then add the following:
```
[wsl2]
guiapplications=false
```

Then open terminal and run command:
`wsl --shutdown`

and then open again Ubuntu / Kali / Centos / Debian .

Hope this helps someone.

**Comment by kinglionsz** [comment] 2021-06-03 13:39
> @hajekj how i can get my wsl.etl

To do so, first download [wsl.wprp](https://github.com/microsoft/WSL/blob/master/diagnostics/wsl.wprp), then run in an administrative command prompt:

`$ wpr -start wsl.wprp -filemode`
Once the log collection is started, reproduce the problem, and run:

`$ wpr -stop wsl.etl`
This will stop the log collection and create a file named wsl.etl that will capture diagnostics information.

pls see:
https://github.com/microsoft/WSL/blob/master/CONTRIBUTING.md#record-wsl-logs-manually

**Comment by StarNamer** [comment] 2021-06-13 00:52
After the most recent Windows Insider Preview updates (Build 21390.1000 and now 21390.1010) I can't get either my Debian or Ubuntu installations to start. Both simply report:

    The parameter is incorrect.
    Press any key to continue...

I've tried setting guiapplications to both true and false and executing 'wsl --shutdown' after changing and neither state works. A few weeks ago, GUI applications were working fine for me.

Docker (confgiured for WSL2) claims to be running, but doesn't respond to a 'docker ps' command from Powershell.

**Comment by onomatopellan** [comment] 2021-06-13 09:28
@StarName That message appears when the vNIC for WSL2 can't be created. Try resetting your network: https://www.howtogeek.com/265870/how-to-reset-your-entire-network-in-windows-10-and-start-from-scratch/

**Comment by StarNamer** [comment] 2021-06-13 09:45
I was getting the message "The parameter is incorrect" which I thought was due to the guiapplications setting. It was actually fixed by reverting to using Windows Console Host instead of Windows Terminal Preview. Apparently noting to do with the network either.

It would help if the message was less ambisuous about whee the issue is!
