### ISSUE TITLE
emacs keep openning new window when start from win10 start menu

### ISSUE THREAD

**Issue by smallst** [microsoft/wslg#132] opened 2021-04-30 03:04 UTC
# Environment

```none
Windows build number: 21370.1
Your Distribution version: 5.10.16
Your WSLg version: 1.0.17.1
```

# Steps to reproduce
install emacs, and install a configuration . i.e. my config: https://github.com/smallst/emacs.d/tree/develop
then start emacs from win10 start menu.

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`
```
pawned Xwayland server, pid 439
[10:56:15.908] xfixes version: 5.0
[10:56:15.918] created wm, root 935
[10:56:17.494] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[10:56:17.494] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[10:56:17.494] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[10:56:17.539] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[10:56:17.539] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[10:56:17.539] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[10:56:17.539] Client: ClientGetAppidReq: pid:404 appId:Emacs
[10:56:18.347] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[10:56:18.347] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[10:56:18.347] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[10:56:18.381] shell_blend_overlay_icon: app 48x48; overlay 128x128; scale 4.67x4.67
[10:56:18.381] rdp_rail_set_window_icon: original icon width:48 height:48 format:537036936
[10:56:18.381] rdp_rail_set_window_icon: converted icon width:48 height:48 format:537036936
[10:56:18.381] Client: ClientGetAppidReq: pid:422 appId:Emacs
...
```
You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior

an emacs app start with configuration

# Actual behavior
emacs app start and stop loading configuration then open another emacs app (see the log) then another then another then another ... can't stop openning new emacs window, and every window is stuck.

btw, start emacs from wsl shell (terminal) works fine. and start eamcs -Q (without configuration) works fine. so i think maybe some env issues?

**Comment by hideyukn88** [comment] 2021-04-30 18:29
@smallst , thanks for reporting, this looks same issue as https://github.com/microsoft/wslg/issues/64.

**Comment by spronovo** [comment] 2021-04-30 23:39
Resolving as a duplicate of #64.

**Closed by spronovo** 2021-04-30 23:39 UTC
Labels: bug, duplicate
