### ISSUE TITLE
Small Resolution when opening GUI on WSL on 4K monitor

### ISSUE THREAD

**Issue by wa1618i** [microsoft/wslg#148] opened 2021-05-03 03:34 UTC
I have 4K monitor. The GUI resolution (font size, graphical interface) is smaller than Windows application. How can I adjust it to fit perfectly to my 27 inch 4K monitor?

**Comment by zhaobingchun** [comment] 2021-05-03 03:51
same problem，i think it can be slove by modify /etc/xdg/weston/weston.ini  [output] scale=1.5, but nothing happend

**Comment by spronovo** [comment] 2021-05-03 05:57
Thanks for your report. We've currently disabled fractional scaling due to poor filtering quality. It will be re-enabled in some future released, this is tracked by issue #23.

Note that you can use 200% DPI scaling today and that will scale correctly.

Closing as a duplicate of #23

**Closed by spronovo** 2021-05-03 05:57 UTC
Labels: bug, duplicate
