### ISSUE TITLE
Scrolling with touchpad get weird sometimes

### ISSUE THREAD

**Issue by SmartPolarBear** [microsoft/wslg#212] opened 2021-05-18 13:17 UTC
# Environment

Windows build: 21382.1
Distribution: debian 11
WSLG : 1.0.21

# Steps to reproduce

Scroll up and down with touchpad. 

#  Expected behavior

It should scroll to some certain direction

# Actual behavior

Sometimes it keeps shaking up and down violently even though you scroll towards only up, or down.
This doesn't happen in 1.0.19 but happens once in a while in 1.0.20. It happens often in 1.0.21

**Comment by spronovo** [comment] 2021-05-18 14:44
Hello, in which app are you seeing this?

**Comment by SmartPolarBear** [comment] 2021-05-19 00:43
> Hello, in which app are you seeing this?

CLion

**Comment by Carobit** [comment] 2021-05-28 07:06
Hi, same or similar issue on WSLg ( x86_64 ): 1.0.22. Strange but i have problem only scrolling downwards (especially fast scrolling). Scrolling up seems to work fine both with touchpad and mouse. 
Scrolling down is shaking, jerky most of the times using the touchpad. Though scrolling very very slowly is ok. 
Using a mouse, the situation is much better, but still scrolling pretty fast (eg logitech free spin wheel) it's just shaking.

Tested on HP ProBook 455 G7
WSLg ( x86_64 ): 1.0.22
Win 10 Pro 10.0.21390
Reproduced on in phpStorm and gedit.

**Comment by SmartPolarBear** [comment] 2021-05-29 08:46
> Hi, same or similar issue on WSLg ( x86_64 ): 1.0.22. Strange but i have problem only scrolling downwards (especially fast scrolling). Scrolling up seems to work fine both with touchpad and mouse.
> Scrolling down is shaking, jerky most of the times using the touchpad. Though scrolling very very slowly is ok.
> Using a mouse, the situation is much better, but still scrolling pretty fast (eg logitech free spin wheel) it's just shaking.
> 
> Tested on HP ProBook 455 G7
> WSLg ( x86_64 ): 1.0.22
> Win 10 Pro 10.0.21390
> Reproduced on in phpStorm and gedit.

It looks like all members of the Jetbrains' family have this issue ?

**Comment by hoangnm205** [comment] 2021-07-06 09:30
> Hi, same or similar issue on WSLg ( x86_64 ): 1.0.22. Strange but i have problem only scrolling downwards (especially fast scrolling). Scrolling up seems to work fine both with touchpad and mouse.
> Scrolling down is shaking, jerky most of the times using the touchpad. Though scrolling very very slowly is ok.
> Using a mouse, the situation is much better, but still scrolling pretty fast (eg logitech free spin wheel) it's just shaking.
> 
> Tested on HP ProBook 455 G7
> WSLg ( x86_64 ): 1.0.22
> Win 10 Pro 10.0.21390
> Reproduced on in phpStorm and gedit.

I have the same problem on WSLg 1.0.24.
I also have this issue with google chrome.

Tested on Thinkpad T14 Gen 1 AMD

**Comment by otocon** [comment] 2021-07-17 20:42
Same issue with gedit or Intellij.

Tested on Razer Blade 14 2021 with WSLg 1.0.26

**Comment by ayserjamshidi** [comment] 2021-11-01 06:55
Likewise.  I don't encounter any scrolling anomalies when using a mouse but with my laptop's touchpad (Asus G15 2021) it seems conditional. Gesture (2 finger) scrolling up/down slow and quick without lifting my fingers works perfectly fine but the moment I lift my finger and attempt to do fast kinetic scrolling it'll get confused and repeatedly scroll up/down and jitter randomly until the momentum has come to a halt, this does not happen when I do a slow to normal speed kinetic scroll.  It occurs with any WSLg app for me.  CLion, Chromium, ..., gedit.

```
ayserjamshidi@AYSERS-LAPTOP:~$  cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.26+Branch.main.Sha.26ce2c09b86442f3c7f4f6462f770ed2afa76a25
Mariner: VERSION="1.0.20210224"
FreeRDP: b05321cd4e6a862aef76163a69db4e1910245736
weston: 46756d0e77e5c01b5995fbbee6f3ab0db9b30612
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:
```

Stock WSL kernel and the most up-to-date packages (as of Nov 1st, 2021) with no added third party repos.

**Comment by vo-ch** [comment] 2021-11-22 11:06
same issue like in comment above, same versions
"the moment I lift my finger after doing a fast kinetic scroll it'll get confused and repeatedly scroll up/down"
Reproduced in google chrome, webstorm .

**Comment by miszczu** [comment] 2022-11-29 21:55
Looks like it was fixed in the recent version. I have just updated to the version from Microsoft Store, and the issue seems gone now.
```
WSL version: 1.0.0.0
Kernel version: 5.15.74.2
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.819
```

**Comment by hideyukn88** [comment] 2022-11-29 23:47
@miszczu, yes, this issue has been fixed in Store version, thanks!

**Closed by hideyukn88** 2022-11-29 23:47 UTC
Labels: bug
