### ISSUE TITLE
Maximising gitkraken makes maximise / minimise buttons disappear and draws outer frame outside of taskbar

### ISSUE THREAD

**Issue by HnLn** [microsoft/wslg#520] opened 2021-10-17 10:51 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.258]
Your Distribution version: Ubuntu 20.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

Maximise the gitkraken window.

#  Expected behavior

The window should be maximised within the desktop (not over the taskbar) and the max / min / close button should remain visible.

The window border should stay within the desktop.

# Actual behavior

The maximise and close button disappear also hovering over the icon in taskbar, the close button in window popup also doesn't work.

![status_bar](https://user-images.githubusercontent.com/5806950/137624028-dd2c9875-3edd-4ac3-a63a-b44f8f3df134.png)

The outer frame expands to the whole screen, over the windows taskbar.

![border](https://user-images.githubusercontent.com/5806950/137624071-89b02946-a647-4f61-908b-f719847cbd06.png)

**Comment by akpatternica** [comment] 2021-10-18 07:36
it is not about gitkraken. it is about all windows which not control their header like firefox and chrome:( But not like gedit. Maybe it is because rounded corner in windows 11.

**Comment by HnLn** [comment] 2021-10-19 20:34
[weston.log](https://github.com/microsoft/wslg/files/7376479/weston.log)

**Comment by hideyukn88** [comment] 2021-10-21 22:16
@HnLn, thanks for the log file and analysis. I tried to reproduce at my end, by setting display scaling to 250%, but it looks maximizing window is working correctly. Is there additional steps I might be missing? And does this issue only happen with gitkraken? how about other GUI applications? Thanks!

**Comment by KoushikSahu** [comment] 2021-11-06 12:40
I am facing the same issue with some AUR packages and some built from source softwares. Did someone find any fix for this?

**Comment by dvelaren** [comment] 2021-11-09 20:24
I have the same issue with wslg and gitkraken

**Comment by HnLn** [comment] 2021-11-14 13:50
Soething else I noticed, the splash screen of the apps (both phpstorm en gitkraken) don't start centered on the desktop, they are more bottom right, so the might not now the actual desktop size ?

I tried to play a bit by going into wsl --system and modify /home/wslg/.config/weston.ini to add mode= with my windows desktop resolution.  At one time I got it starting centered and it maximised correctly, but then I realised the changes to weston.ini are not retained, so I'm not sure if it indeed did something and I can't reproduce either ... :).

**Comment by HnLn** [comment] 2021-11-20 19:57
FYI on a fresh win11 and microsoft store wsl install the issue is gone.

**Closed** 2021-11-30 19:32 UTC
Labels: bug
