### ISSUE TITLE
Vulkan development support...

### ISSUE THREAD

**Issue by wmarti** [microsoft/wslg#191] opened 2021-05-12 16:13 UTC
**Is your feature request related to a problem? Please describe.**
Vulkan appears to not currently be supported with wslg. I much prefer unix-style development on Windows using VsCode and WSL, and really dislike being forced to use Visual Studio or switch to a native linux environment.

**Describe the solution you'd like**
Full Vulkan support for native-like development in wslg.

**Describe alternatives you've considered**
Moving to Linux, which I've decided to do for Vulkan development, as I personally dislike the native windows development style through Visual Studio.

**Comment by hideyukn88** [comment] 2021-05-12 18:13
@wmarti , thanks for suggestion, is your requirement covered by https://github.com/microsoft/wslg/issues/40 ? thanks!

**Comment by wmarti** [comment] 2021-05-12 21:25
As long as Vulkan Development would be supported!

**Comment by spronovo** [comment] 2021-05-22 02:57
Thanks for your report. Closing this one as a duplicate of #40.

**Closed by spronovo** 2021-05-22 02:57 UTC
Labels: enhancement
