### ISSUE TITLE
Cut-n-paste between X11 apps and Windows

### ISSUE THREAD

**Issue by Michael-Sinz** [microsoft/wslg#721] opened 2022-04-22 15:31 UTC
With WSL 2 support for GUI (X11) applications, I no longer need to set up a local X11 server on Windows.
However, I may yet have to do that since the clipboard does not work.

That is, I am running a standard X11 tool that runs with the X11 implicit clipboard highlight and paste.  (It is rxvt but traditional xterm would also be the same)

Anyway, between two X11 windows (two rxvt windows) I get the right cut-n-paste behavior but I can not paste the results into a Windows window (say Notepad or VS Code) nor can I paste something I cut from Windows into the X11 terminals.

This is a major flaw and something that makes it very hard to work in the environment with Windows 11 and the WSL compared to Windows 10 and WSL and a Windows X11 server (specifically, I have been using  VcXsrv https://sourceforge.net/projects/vcxsrv/ before Windows 11)

Could we get cut-n-paste to work across WSL GUI and Windows or do we need to figure out how to run our own X11 server software again?

**Comment by hideyukn88** [comment] 2022-04-22 16:57
@Michael-Sinz, would you please double check if you are using WSL from aka.ms/wslstorepage, not the one from Windows's optional features. We have fixed various issues with clipboard in newer release from Store. Also, WSLg does not yet support copy by primary selection from X11, thanks!

**Comment by Michael-Sinz** [comment] 2022-04-22 18:11
@hideyukn88,  I am using the one from the store - installed last night

It is the primary selection from X11 - I use actual rxvt windows for my xterm (as I have lots of tools that throw new windows for status/etc)

The problem right now is that I can't cut-n-paste results from those windows into anything on the Windows side.  If I open up a Linux X11 notepad or VSCode on the Linux side it works but nothing works to the Windows side.

In Windows 10, I used my own VcXsvr installation and this was working wonderfully - I have yet to figure out what to do here with Windows 11 and the implementation there.  I may have to revert to VcXsrv to have a working environment again - which would be very unfortunate given that otherwise this works nicely.

**Comment by hideyukn88** [comment] 2022-04-22 20:08
Close as duplicate of https://github.com/microsoft/wslg/issues/642

**Closed by hideyukn88** 2022-04-22 20:08 UTC
Labels: bug, clipboard-integration
