### ISSUE TITLE
baudline exits with BadWindow

### ISSUE THREAD

**Issue by shuffle2** [microsoft/wslg#493] opened 2021-10-08 18:22 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.22000.194]
Your Distribution version: Release:        21.04
Your WSLg version: 1.0.26
```

# Steps to reproduce

Download and extract baudline from e.g. https://www.baudline.com/baudline_1.08_linux_x86_64.tar.gz
(see https://www.baudline.com/download.html for instructions from author if needed).

#  Expected behavior

baudline application executes without errors and displays windows.

# Actual behavior

```
$ ./baudline
could not open 10x20 font
could not open 5x7 font
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  532
  Current serial number in output stream:  533
```
(application exits)

It's possible there is some simple workaround, but I'm not quite sure what the actual issue is, nor familiar with X/weston/etc.

The application did work when I was using vcxsrv.

**Comment by dpeterc** [comment] 2021-10-09 21:36
The error from Baudline is telling you that it is searching for a hardcoded / failback fixed size font 10x20 and 5x7, and that it is unable to work without them, so it closes down.

The problem is with wslg, which uses custom Linux distribution to run modified xorg server within wayland. Apparently is comes with very reduced font set, with respect to normal Linux distribution.

You can list the installed fonts by typing
xlsfonts
Probably fonts 20x20 and 5x7 will not be on the list, so this is the reason why Baudline fails to start correctly.
But if you install additional fonts on your Linux distribution withing wslg, for example xorg-x11-fonts-core these are not passed on  / registered properly in the X11 server. So the list of fonts resulting from xlsfonts command remain the same.

So your bug is actually a variation of "Fonts installed but not available"
https://github.com/microsoft/wslg/issues/310

**Comment by shuffle2** [comment] 2021-10-09 21:52
thanks @dpeterc I can confirm it seems to be the same issue.

**Comment by voltagex** [comment] 2023-03-12 13:02
I can confirm that installing `xfonts-base` on the default Ubuntu WSLg installation, then *terminating* and restarting WSL will allow baudline to work.

![image](https://user-images.githubusercontent.com/83080728/224546317-dcafc6fa-57bc-44b5-830d-9ed2b24affb7.png)

This was fixed with https://github.com/microsoft/wslg/pull/824.

I am on Windows 11 Insider, I am not sure what version of Windows you need but it works at the time of writing.

**Closed as completed** 2023-03-12 20:55 UTC
Labels: bug
