### ISSUE TITLE
Alt_gr key stops working in german keylayout when using wslg

### ISSUE THREAD

**Issue by MTRNord** [microsoft/wslg#88] opened 2021-04-24 16:27 UTC
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.21364.1]
Your Distribution version: Ubuntu 21.04
Your WSLg version: 1.0.17.1
```

# Steps to reproduce

1. Use a german ISO keyboard with german keyboard layout.
2. Press things like ALT_GR+ß

Expected: Returns \
Reality: Returns ß

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl$\<Distro-Name>\mnt\wslg` (e.g.: `\\wsl$\Ubuntu-20.04\mnt\wslg`)

* [pulseaudio.log](https://github.com/microsoft/wslg/files/6370129/pulseaudio.log)
* [weston.log](https://github.com/microsoft/wslg/files/6370130/weston.log)
* `versions.txt` (No permission apparently and 0 bytes)

#  Expected behavior

When using alt_gr it should be registered

# Actual behavior

Modifier key alt_gr doesnt get recognized

# Possible related cause

According to https://superuser.com/a/1245750 this is most likely due to how RDP in windows 10 behaves.

**Comment by MTRNord** [comment] 2021-04-24 16:32
Workaround is to run `wsl --shutdown` as that closes the RDP connection

**Comment by hideyukn88** [comment] 2021-04-24 19:28
@MTRNord , it looks RDP/WSLg recognize the keyboard layout.

[11:49:17.336] kbd_layout:0x407 kbd_type:0x4 kbd_subType:0x0 kbd_functionKeys:0xc
[11:49:17.336] convert_rdp_keyboard_to_xkb_rule_names: matching layout=de variant=(null)

#define KBD_GERMAN 0x00000407

Would you check if keyboard layout and locale are configured in your user-distro? Please refer https://github.com/microsoft/wslg/issues/27.

**Comment by MTRNord** [comment] 2021-04-24 20:56
@hideyukn88 Thanks I will check that tomorrow. 

But just as added clarity this issue happens in the pure windows applications. So not only linux apps (in fact I actually didnt verify if this happens in linux apps).

**Comment by spronovo** [comment] 2021-04-25 22:09
@MTRNord for issue with Windows application, could you open an issue through the Feedback Hub (open start menu and search for "feedback" it should come right up). This particular project is tracking problem specifically for WSLg.

**Comment by MTRNord** [comment] 2021-04-25 22:11
@spronovo ao the issue is that the issue here is caused by wslg. Aka if I stop it: windows behaves normal. If I use it is Breaks alt gr. But sure I will Do it via the Feedback way :/

**Comment by spronovo** [comment] 2021-04-25 22:18
@MTRNord i apologize, i hadn't realize the link to WSLg... if this happen once when WSLg is enable we'll take the first look, no need to open a bug through the feedback up then.

**Comment by hideyukn88** [comment] 2021-04-26 15:27
@MTRNord , could this be same issue as below? As you pointed out, WSLg is utilizing mstsc.exe as well.

https://stackoverflow.com/questions/23482392/altgr-key-not-working-instead-i-have-to-use-ctrlaltgr

**Comment by hideyukn88** [comment] 2021-04-27 17:56
@MTRNord , we are having difficulties to reproduce this issue locally here, and we wonder if this requires physical Garman keyboard, which we don't have. If possible, would you please try using Windows Virtual Keyboard with Garman layout to see if it reproduce same problem ? Thanks!

**Comment by MTRNord** [comment] 2021-04-27 18:01
It seems like for some reason I cannot anymore reproduce it either. I am not sure if maybe some update fixed it by accident. But currently running wslg it works fine. 

The stackoverflow article you linked was the thing that was also my guess on what happened as ctrl was the key making it temporary working as well for me.

I will look out for it more now and double check when it happens.

**Comment by MTRNord** [comment] 2021-04-27 18:05
Maybe I pressed some keyboard combination that switched a mode in the mstsc.exe by accident? I am not too familiar what it does and what keybindings it might capture. I was using a lot of keybindings when it happened due to doing some coding right before. So there is a high chance that that caused it but I am not quite sure. But I can confirm it is the exact thing thats described in the stackoverflow issue just that I have that on my local running software instead of in the remote software. The linux software side didnt have any issues. But firefox,typora,discord and others on windows had it until I force stopped wsl.

**Comment by Matsemann** [comment] 2021-06-01 09:06
I just had it happen to me. Alt gr started behaving as a normal alt, in normal windows applications. (Using norwegian layout)

Pressing alt+enter in a normal windows window didn't fix it.
But bringing up a window from wslg and pressing alt+enter there, fixed it. Dunno why. 

Found the tip here: https://superuser.com/a/1245750

**Comment by hideyukn88** [comment] 2021-07-20 17:37
Hi. Windows RDP client software team found the issue in mstsc.exe, this will be fixed in future release of Windows. thanks!

**Closed** 2021-10-07 21:11 UTC
Labels: bug, keyboard-layout

**Comment by adesso-os** [comment] 2022-12-16 11:44
Given this was closed over a year ago, which "future release of Windows" are we waiting for to have this behavior fixed?

**Comment by marbon87** [comment] 2023-01-11 15:29
Is there a workaround until this is fixed?

**Comment by hideyukn88** [comment] 2023-01-11 18:00
@marbon87, @adesso-os, thanks for inquiry, the fix should be included in current release of WSLg, and as I tried out below, it looks AltGr + 'q' and AlrGr + 'm' on German keyboard layout produces the expected results on both Windows's noteadpad as well as Linux's gedit (see below screen capture running them side by side). Just for reference, below is the link to Windows's German keyboard layout, you can click AltGr key to see what results should be expected with the combination, thanks!

![image](https://user-images.githubusercontent.com/13857962/211882220-e22773bb-8a25-4ded-a4ab-b0c44235d80c.png)

https://learn.microsoft.com/en-us/globalization/keyboards/kbdgr

![image](https://user-images.githubusercontent.com/13857962/211881303-0c09311e-c9a8-436e-aa23-9c989d3a6bcc.png)

**Comment by marbon87** [comment] 2023-01-12 07:00
Thanks for the quick feedback  @hideyukn88 .

I have the latest version of wsl-g (1.0.47), but i still cannot use altgr + y to type an umlaut (e.g. ü)  with this keyboard layout settings:
```
setxkbmap -layout us -variant altgr-intl -model pc105 -option nodeadkeys
```

Also with german layout (setxkbmap -layout de) altgr + q isn't working. 

This is my environment

```
> lsb_release -r
Release:        20.04

> wsl --version
WSL-Version: 1.0.3.0
Kernelversion: 5.15.79.1
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19044.2486
```

**Comment by adesso-os** [comment] 2023-01-12 08:59
It's definitely not working for me either. I read elsewhere that my custom keyboard layout on Windows is to blame, but the AltGr works as expected on Windows and on a WSL console. So I feel like I could expect it to work in WSLg as well.

**Comment by hideyukn88** [comment] 2023-01-12 16:55
@marbon87, WSLg automatically match Linux side keyboard layout with currently selected keyboard layout at Windows side, so basically no need to do setxkbmap, and according to https://learn.microsoft.com/en-us/globalization/keyboards/kbdgr, AtlGr + 'y' is not assigned to anything. If key is not assigned at Windows side, no input to be sent to WSLg, thus even xkb has some assignment for that combination, it won't produce any input, thanks!

@adesso-os, currently WSLg doesn't work properly with custom keyboard layout which is tracked by https://github.com/microsoft/wslg/issues/173. So I think, in your case, Linux side is default to English layout in Linux side, thus AltGr is not working, thanks!

**Comment by marbon87** [comment] 2023-01-13 07:04
@hideyukn88 AltGr + 'y' is mapped to ü also on windows side on United States-International Keyboard:

![image](https://user-images.githubusercontent.com/2949525/212258035-c928fbde-1191-4711-9596-14c33d027bd2.png)

https://learn.microsoft.com/en-us/globalization/keyboards/kbdusx

It is working on windows and in the terminal, but not in wslg

**Comment by hideyukn88** [comment] 2023-01-17 20:10
@marbon87, my previous reply is regarding to German keyboard layout. With US international, AltGr + y also works same way for WSLg as well as Windows's native. gedit (at Linux) and notepad (at Windows) with AltGr + y is showing they produce same output at below, thanks!

![image](https://user-images.githubusercontent.com/13857962/213001334-7144e687-1e77-4aab-949a-a8f878b04b23.png)

**Comment by marbon87** [comment] 2023-01-18 07:40
Thanks for your feedback @hideyukn88. I forgot that i use a custom keyboard layout with dead keys (https://github.com/umanovskis/win-kbd-usint-nodead/), which seems to be the cause. With Us internation, altgr + y works fine.
