### ISSUE TITLE
Graphics / Display is not loading

### ISSUE THREAD

**Issue by imPrashik** [microsoft/wslg#825] opened 2022-09-08 08:59 UTC
### Windows build number:

22000.856

### Your Distribution version:

22.04

### Your WSL versions:

WSL version: 0.66.2.0

![image](https://user-images.githubusercontent.com/4114326/189080184-10824764-a70c-40c1-b1f9-23e3e5faa1cd.png)
![image](https://user-images.githubusercontent.com/4114326/189080345-a0dd43b7-076b-4698-b12e-114ed2f6df94.png)
[weston.log](https://github.com/microsoft/wslg/files/9525351/weston.log)

### Steps to reproduce:

Installed chrome.deb package

unable to launch

### WSL logs:

[weston.log](https://github.com/microsoft/wslg/files/9525358/weston.log)

### Expected behavior:

Graphics chrome window should launch

### Actual behavior:

![image](https://user-images.githubusercontent.com/4114326/189080914-56e3d144-66c8-493f-8f5b-b48aaccc58f7.png)

**Comment by hideyukn88** [comment] 2022-09-08 16:29
@imPrashik, thanks for reporting the issue, do you see /tmp/.X0-lock in system distro? please try below, `wsl --system` from Windows command prompt let you enter system distro, thanks!

<img width="474" alt="image" src="https://user-images.githubusercontent.com/13857962/189175906-594de401-407e-4e3a-9f95-081750a7ef12.png">

**Comment by hideyukn88** [comment] 2022-09-08 18:14
@imPrashik, I think we understand the issue, but would like to double check, do you install and run multiple Linux distro on WSL? thanks!

**Comment by imPrashik** [comment] 2022-09-12 07:27
> @imPrashik, I think we understand the issue, but would like to double check, do you install and run multiple Linux distro on WSL? thanks!

No @hideyukn88, I have only one distro.

![image](https://user-images.githubusercontent.com/4114326/189596436-39d48ac0-9751-4fe0-8428-d64a75ffb661.png)

previously I had ubuntu, I uninstalled and installed it back for cross checking network issue which was caused by Bitdefender

**Comment by hideyukn88** [comment] 2022-09-15 20:34
@imPrashik, would you please share the contents of /tmp at system-distro? see https://github.com/microsoft/wslg/issues/825#issuecomment-1240947457, thanks!

**Comment by mentalisttraceur** [comment] 2022-09-28 20:08
Similar issue. Setting the `DISPLAY` environment variable to something higher than `:0` worked for me.

`:1` is working from my Ubuntu distro, which I started first but which I installed only recently.

`:3` is working from my Debian distro, which I started second but which I installed a really long time ago (it was actually originally a WSLv1 distro, which I upgraded to WSLv2 sometime after that became available).

The contents of `/tmp/.X11-unix` are a socket named `X1` in the Ubuntu distro and a socket named `X3` in the Debian distro - that's probably related to why only those two worked.

I got the idea to test higher `DISPLAY` numbers because of the discussion here.

@hideyukn88 could you elaborate how/why having multiple distros WSL distros messes this up?

**Comment by hideyukn88** [comment] 2022-09-28 20:24
@mentalisttraceur,

>> @hideyukn88 could you elaborate how/why having multiple distros WSL distros messes this up?

Recently, there was an attempt to optimize resource usage of system-distro, by sharing same file mapping across multiple user-distro, this cause /tmp in system-distro to be shared across multiple user distro accidentally, and because below code in weston, it saw the lock file from other distro, which ends up incrementing DISPLAY number and creates the socket with incremented number, thus this causes mismatch between actual port configured in system distro and environment variable in user distro, thanks!

https://github.com/microsoft/weston-mirror/blob/86c7175dff9e95a55ab073cf1cf256c9f942d498/xwayland/launcher.c#L272

**Comment by mentalisttraceur** [comment] 2022-09-28 20:55
Cool, thanks for the explanation!

Something I still don't get is how exactly I got into a state where display zero and display two were both taken by something other than the two distros I have installed.

After exiting both my Ubuntu and Debian shells from the above example:

1. Started Debian, the default `DISPLAY` of `:0` worked fine, and `/tmp/.X11-unix` has `X0`.

2. Started Ubuntu, needed to set `DISPLAY` of `:1`, and `/tmp/.X11-unix` has `X1`

3. Started a second Debian terminal through Windows Start Menu. Display is 0.

4. Started a second Ubuntu terminal through Windows Start Menu. Needed to use display 1.

5. Exited both Debian terminals and one Ubuntu terminal. Created one more Debian terminal, where display 0 works. Exited Debian again. Just one Ubuntu left with display 1.

6. Started `wsl --system` from PowerShell for good measure. (I thought this might help replicate the using up of `:2` which I saw during my last run.)

7. Started Debian again. Display is 0.

So it seems like it normally starts at zero and reuses zero after the distro which used zero closes.

Then again the situation in my last comment was soon after running a `sudo do-release-upgrade` in the Ubuntu instance, which seemed to do some sort of WSL-specific magic (including asking me to close the WSL instance it was running in, followed by printing some message about detaching). So if that process created two extra internal WSL instances at some moments in the process, that might explain how I got into the state that I did.)

Okay, well, with that figured out, it seems like my problem was slightly different than the one being reported in this Issue, so I'll tap out now before I derail it even more. Thanks again!

**Comment by hideyukn88** [comment] 2022-09-28 21:05
@mentalisttraceur, if acceptable, would you please update to current prerelease version of WSL? which can be downloaded from https://github.com/microsoft/WSL/releases/tag/0.68.2 (download .msixbundle and double click file to install), this addresses the sharing the issue I mentioned above, thanks!

**Comment by sstavridis** [comment] 2022-09-29 10:19
@hideyukn88 I have the same issue on one of my three distros. Can you give me a tip?

```
develke@DESKTOP-NI485FJ:~$ ls -la /tmp/.X11-unix
total 40
drwxrwxrwx   2 root root    40 Sep 29 12:47 .
drwxrwxrwt 584 root root 36864 Sep 29 12:43 ..
```
```
develke@DESKTOP-NI485FJ:~$ ls /tmp/.X11-unix
develke@DESKTOP-NI485FJ:~$
```
This is what I'm getting with the problematic distro.

But when I run the same command on the other distros I get these results:

```
sstavridis  ~  ls -la /tmp/.X11-unix
total 24
drwxrwxrwx 2 root       root          60 Sep 29 12:21 .
drwxrwxrwt 7 root       root       20480 Sep 29 12:46 ..
srwxrwxrwx 1 sstavridis sstavridis     0 Sep 29 12:21 X0
```
```
sstavridis  ~  ls /tmp/.X11-unix
X0
```

**Comment by mentalisttraceur** [comment] 2022-10-02 02:25
@hideyukn88 yep, just installed 0.68.2 from the link you gave, and it indeed fixed the issue! thanks!

**Comment by MisterT87** [comment] 2022-10-04 09:47
Just want to tell: Had the same issue - After Installing WSL Pre-Release (v.0.68.2) manually
(Downloaded .msixbundle-File from: [https://github.com/microsoft/WSL/releases/tag/0.68.2](https://github.com/microsoft/WSL/releases/tag/0.68.2) )
No Problems anymore - x11 Apps just working fine (without using separate X11 Server).

Just download this File from github and Install it by double click (Close alle WSL instances before!).
No need to change `$DISPLAY` variable !

Using Ubuntu 22.04 LTS from Microsoft Store.
if you want compare WSL version (After installing WSL 0.68.2):
`wsl -v`
`WSL-Version: 0.68.2.0`
`Kernelversion: 5.15.62.1`
`WSLg-Version: 1.0.44`
`MSRDC-Version: 1.2.3401`
`Direct3D-Version: 1.606.4`
`DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp`
`Windows Version: 10.0.22000.1042`

**Comment by mentalisttraceur** [comment] 2022-10-06 04:17
@hideyukn88 Do you know if upgrading to the preview version still breaks executing wsl.exe through SSH?

For example, in CMD or PowerShell prompt: `ssh localhost` -> type in password -> `wsl` -> get "The file cannot be accessed by the system." error as terminal output.

**Comment by hideyukn88** [comment] 2022-10-07 17:19
@mentalisttraceur, unfortunately upgrading preview version of WSL won't fix that. This requires changes in Windows OS side and we are working with corresponding teams, but no ETA at this point, thanks!

**Comment by hideyukn88** [comment] 2022-10-12 23:41
Hi all, regarding to X server connection issue, WSL 0.70.0 is just released and this should address the issue, please update it by `wsl --update`, and if the problem still persists, please let us know by reopening this issue, thanks!

**Closed by hideyukn88** 2022-10-12 23:41 UTC
Labels: bug, fixinbound

**Comment by wangzhiqiang** [comment] 2022-10-18 14:37
[weston.log](https://github.com/microsoft/wslg/files/9811486/weston.log)
WSLg ( x86_64 ): 1.0.45+Branch.main.Sha.254cbbc0eb26fe4bf82e9656470ebb5546a84a23
Mariner: VERSION="2.0.20220426"
DirectX-Headers:
mesa:
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
FreeRDP: c574044a10003e50453acb4cf42801c5833fb572
weston: 2270ceb3cf75a03e8b3f073eca2c5dc04b12e504

wzq@ArrowDown:/mnt/aosp$ ls /tmp/.X11-unix
X0
wzq@ArrowDown:/mnt/aosp$ ls -la /tmp/.X11-unix
lrwxrwxrwx 1 root root 19 10月 17 22:38 /tmp/.X11-unix -> /mnt/wslg/.X11-unix
wzq@ArrowDown:/mnt/aosp$ echo $DISPLAY
:0

**Comment by wangzhiqiang** [comment] 2022-10-20 12:38
It's missing lib "xcb". after install xcb aosole can not run aosp emulator.and VLC running well

run VLC
![image](https://user-images.githubusercontent.com/2043458/196949678-3494cb04-70dc-4f88-99a3-d774d6240fdc.png)

run aosp emulator

![image](https://user-images.githubusercontent.com/2043458/196949885-836eee01-feb9-4900-8b94-e7a78066abe5.png)


dmesg

![image](https://user-images.githubusercontent.com/2043458/196949967-5289732c-2ad8-4441-8129-8e21a90f6b74.png)



and run emulator with android studio
![image](https://user-images.githubusercontent.com/2043458/196950589-e87aa566-e6d5-425a-bfb1-d792ea1fdb0d.png)

**Comment by wangzhiqiang** [comment] 2022-10-20 12:48
[core.zip](https://github.com/microsoft/wslg/files/9830142/core.zip)
this is dump file  core.weston

**Comment by hideyukn88** [comment] 2022-10-20 15:29
@wangzhiqiang, thanks for dump, would you please provide more details on how do you reproduce this issue step by step? The problem seems this utility window (_NET_WM_WINDOW_TYPE_UTILITY) gets transient_for property (XCB_ATOM_WM_TRANSIENT_FOR) after shell surface is created, I would like to understand how this is happening, thanks!

**Comment by wangzhiqiang** [comment] 2022-10-21 07:35
same step to #802 
![image](https://user-images.githubusercontent.com/2043458/197139458-5f8d9ff6-e951-42e5-82fd-a676b89ede1d.png)

**Comment by hideyukn88** [comment] 2022-10-21 12:19
@wangzhiqiang, after you launch the emulator, is there anything need to be done with emulator window for reproducing the issue? thanks!

**Comment by wangzhiqiang** [comment] 2022-10-21 13:12
do nothing.

**Comment by hideyukn88** [comment] 2022-10-24 21:25
@wangzhiqiang, thanks, now I'm able to reproduce the issue, it exhibited same problem seen in the core dump provided by you, I made a fix and confirmed now it's working and operatable, and given the issue you reported fits more on https://github.com/microsoft/wslg/issues/802, so I will track there, thanks

![image](https://user-images.githubusercontent.com/13857962/197631880-b6503a15-7c6f-499c-8541-f37d052222fa.png)

**Comment by TadeoArmenta** [comment] 2022-12-03 11:34
Same issue here.
Ubuntu 22.04

![image](https://user-images.githubusercontent.com/10125168/205438896-c9b7c233-a77d-4344-b0ae-032b8a418276.png)
![image](https://user-images.githubusercontent.com/10125168/205438920-e3310021-35e4-46cd-b48f-fdc4e79635b2.png)
