### ISSUE TITLE
[process exited with code 4294967295]

### ISSUE THREAD

**Issue by AtilaLavor** [microsoft/wslg#49] opened 2021-04-22 19:38 UTC
# Environment

```
Windows 10 Pro build 21364.co_release.210416-1504
Ubuntu 20.04
```

# Steps to reproduce

```
1. Update Windows
2. Update WSL to support WSLg
2. Run the distro


I updated my Windows to build 21364 and then ran the command WSL --update as directed by the website https://github.com/microsoft/wslg.

Instruction:
"Updating WSL + WSLg
To update to the latest version of WSL and WSLg released for preview, simply run wsl --update from an elevated command prompt or powershell. "

When I restarted the computer, I was unable to access the WSL and presented the following error:

The parameter is incorrect.
[process exited with code 4294967295]

I looked for the .wslconfig file in C: \ Users \ MyUser, to set the parameter below, but it doesn't exist on my computer:
 
[wsl2]
guiapplications = false
```

**WSL logs**:
``` 
attach wsl.etl
```
[wsl.zip](https://github.com/microsoft/wslg/files/6360815/wsl.zip)

#  Expected behavior

```WSL fails to start with:. ```

# Actual behavior

```
 The parameter is incorrect.

[process exited with code 4294967295]
```

**Comment by hideyukn88** [comment] 2021-04-22 23:17
@AtilaLavor, the provided log shows same issue as https://github.com/microsoft/wslg/issues/33, and we are working on the fix.

"A máquina virtual 'Virtual Machine' não pode ser iniciada. A região MMIO superior (0x00000012001ff000) está acima do intervalo de endereços físicos com suporte. Certifique-se de que a região MMIO superior esteja abaixo de 0x0000001000000000. "

**Comment by spronovo** [comment] 2021-04-23 04:24
Closing this as a duplicate of #33, this is the same MMIO configuration failure on older processor supporting only 36bits physical addressing.

**Closed by spronovo** 2021-04-23 04:24 UTC
Labels: bug
