### ISSUE TITLE
WSLg won't work on 4 monitor system

### ISSUE THREAD

**Issue by ldraconus** [microsoft/wslg#122] opened 2021-04-28 19:25 UTC
Error: "Can't open display :0".

Works when I disconnect all of the monitors

It also works with 3 or less monitors ...

**Comment by spronovo** [comment] 2021-04-29 00:27
I suspect you are hitting a known issue (#19)... 4 monitors should work fine, but at the moment all monitors must all be either vertically or horizontally connected, you can mix vertical and horizontal connection or you'll hit a failure in in the RDP backend. A fix for this in on the way with the next release of WSLg. To verify this is indeed the case you are hitting, you can try the following:

```
cat /mnt/wslg/weston.log | grep isConnected_V
```
if you see something like

```
weston: ../libweston/backend-rdp/rdpdisp.c:481: disp_monitor_validate_and_compute_layout: Assertion `isConnected_V == true' failed.
```
Then you are hitting this problem. The workaround at the moment is to stack all of your monitor either vertically, or horizontally but not mix until the fix is release.

**Comment by ldraconus** [comment] 2021-04-29 00:46
Thank you for your quick reply to my report! Unfortunately I can't do that
due to the setup of my office but I will survive until the next update.
I've lasted this long I can wait a little bit.

BTW, that's exactly it...

Chris Olson

**Comment by spronovo** [comment] 2021-04-29 00:51
Thanks for the confirmation. I'll resolve this one as a duplicate of #19.

**Closed by spronovo** 2021-04-29 00:51 UTC
Labels: bug, duplicate
