### ISSUE TITLE
emacs spams one character on start up

### ISSUE THREAD

**Issue by landermkerbey** [microsoft/wslg#215] opened 2021-05-20 00:50 UTC
# Environment

```none
Windows build number: Windows 10 Home, Build 21382.co_release.210511-1416
Your Distribution version: Ubuntu 20.04 LTS
Your WSLg version: 1.0.19
```

# Steps to reproduce

1. Open the WSLg Ubuntu terminal.
2. `emacs .emas.d/init.el &`
3. Make some simple modification to the emacs configuration. I have opted for `(menu-bar-mode -1)`.
4. Save the changes and close emacs.
5. Open any text file in emacs.

#  Expected behavior

I expect emacs to start normally, with the only change being whatever configuration I'd set up in `init.el`.

# Actual behavior

On start-up, a single character will be spammed in the main buffer of emacs. There appear to be three variations on this scenario:

- The letter `c` is spammed until I hit any key on my keyboard. If I do not click on the main buffer at all, this happens at the beginning of the file and proceeds indefinitely until I intervene by pressing a key. If I click on the main buffer in a way that moves point, it resumes spamming the character from point's new location until I press a key.
- The letter `z` is spammed as described above.
- The minibuffer indicates that `C-c` (i.e. Control + C) is being spammed. This will continue until you click on the emacs GUI window, at which point it will revert to the letter `c` behavior described above.

If a WSL session is started without any `init.el` file already existing, then emacs will launch normally until such an `init.el` file is created. After the error starts occurring, the only way I've been able to stop it is to delete `init.el` entirely, close WSL and start a new session, at which point emacs goes back to working properly.

**Comment by cpbotha** [comment] 2021-05-20 04:37
This looks like a duplicate of https://github.com/microsoft/wslg/issues/207

**Comment by spronovo** [comment] 2021-05-22 02:38
Thanks for the report. This is now understood and looks like a duplicate, please see #58 for details.

**Closed by spronovo** 2021-05-22 02:38 UTC
Labels: bug, duplicate

**Comment by saltsucker** [comment] 2022-05-23 16:16
In case anybody else might want help with this. I came across this tutorial:
https://emacsredux.com/blog/2021/12/19/using-emacs-on-windows-11-with-wsl2/

It doesn't directly solve the solution, but installing emacs 29 with `--with-pgtk` seems to have resolved this issue for me. (I had the character spamming with 27+)
