### ISSUE TITLE
Remove start menu entry when a distro is uninstalled/unregistered

### ISSUE THREAD

**Issue by itsme-alan** [microsoft/wslg#127] opened 2021-04-29 03:26 UTC
**Is your feature request related to a problem? Please describe.**

Uninstalling distros won't actually remove the apps from the start menu

**Describe the solution you'd like**

Remove distro apps in the start menu on uninstalling the distro

**Describe alternatives you've considered**

Right Click > More > Open file location > Delete shortcut

**Additional context**

None

**Comment by hideyukn88** [comment] 2021-04-29 15:21
thanks for reporting, this is duplicate of https://github.com/microsoft/wslg/issues/24, and please refer that for workaround, thanks!

**Closed** 2021-04-29 16:10 UTC
Labels: duplicate, enhancement
