### ISSUE TITLE
Pop up Windows sometimes aren't shown correctly 

### ISSUE THREAD

**Issue by craigloewen-msft** [microsoft/wslg#10] opened 2021-02-11 17:57 UTC
# Environment

```none
Windows build number: 21298 rsmaster
Your Distribution version: Ubuntu 20.04
Your WSLG version: 0.2.11
```

# Steps to reproduce

- Install gitkraken (I used the download link and installed the .deb https://www.gitkraken.com/download )
- Run gitkraken
- Open a repository by clicking 'Browse' but do not select one
- Navigate away from the Window and open other Windows infront of it
- Click on gitkraken again
- Only the gitkraken window will pop up, and it will be non-interactable. I'd expect the modal Window to pop up too.

#  Expected behavior

The pop up Window should pop up in place over the git kraken Window.

# Actual behavior

The pop up Window remains hidden behind all other Windows, causing the user to go find it before they can go interact with the app again.

![gif4](https://user-images.githubusercontent.com/42221804/107677729-70771280-6c4f-11eb-879b-4f613746a5bf.gif)

**Comment by JYInMyHeart** [comment] 2021-04-30 01:14
Really hope this problem can be fixed as soon as possible🥺.

**Comment by JYInMyHeart** [comment] 2021-04-30 01:15
Really hope this problem can be fixed as soon as possible🥺.

**Comment by JYInMyHeart** [comment] 2021-05-09 15:47
Really hope this problem can be fixed as soon as possible🥺.

**Comment by hideyukn88** [comment] 2021-05-10 01:35
@JYInMyHeart , thanks for your feedback. I just submit the fix for this issue. Once the release with fix is out, please try it, thanks!

**Comment by JYInMyHeart** [comment] 2021-05-10 01:37
> @JYInMyHeart , thanks for your feedback. I just submit the fix for this issue. Once the release with fix is out, please try it, thanks!

OK, no problem. Thank you, too.

**Comment by onomatopellan** [comment] 2021-05-12 11:59
@hideyukn88 I'm testing the fix and now some wayland apps like epiphany browser won't show the menu although you can see it in the taskbar thumbnail and I can open and see the About dialog. With WSLg 1.0.20 it shows the menu but it doesn't show the About dialog.

`sudo apt install epiphany-browser`
`epiphany`

![2021-05-12 (1)](https://user-images.githubusercontent.com/599142/117970572-17d81400-b329-11eb-9aa9-d1f946eff891.png)

```
$ cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): <current>
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 0af13ff2a2d8af2f9a0fe33f6b6a01f06c20a734
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa: 2ad0684038f5732f7e4bd1a391ec9d833685fb48
```

**Comment by hideyukn88** [comment] 2021-05-12 14:53
@onomatopellan , thank you very much for report, I confirmed the issue, it looks wl_subsurface is not properly handled, I will look into more details, thanks!

**Comment by Carobit** [comment] 2021-05-15 06:03
> 
> 
> @JYInMyHeart , thanks for your feedback. I just submit the fix for this issue. Once the release with fix is out, please try it, thanks!

I'm testing the issue with phpStorm popup windows reported in https://github.com/microsoft/wslg/issues/96

Just updated to 21382, but the problem still exists. Is this fix included in the 21382 build?
Running  wsl --update says
Checking for updates...
No updates are available.
Kernel version: 5.10.16

Do I miss something? How should I update WSLg to run on the latest version and test this fix?

Details:
Windows build number: 10.0.21382.0
Distribution version: Ubuntu-20.04
WSLG version: 1.0.19 

cat /mnt/wslg/versions.txt
WSLg ( x86_64 ): 1.0.19+Branch.main.Sha.2a47bf20c239b523d7413f315cbc9ee60dfde831
Mariner: VERSION="1.0.20210224"
FreeRDP: 5f083fa0b97d433d6204985f6047886e29c1c61e
weston: 16de531f00aa3dfd17e0de74c8f49e9fd7cec617
pulseaudio: 2f0f0b8c3872780f15e275fc12899f4564f01bd5
mesa:

**Comment by onomatopellan** [comment] 2021-05-15 13:43
@Carobit There is no need to update the Windows build. Most important part from WSLg is the System distro package that comes via Windows update. You can wait for the updates or also just create a system.vhd with the latest fixes following [the guide](https://github.com/microsoft/wslg/blob/main/CONTRIBUTING.md).

Thanks to latest @hideyukn88 fixes I compiled a new system.vhd and I have no more problems in wayland apps like Epiphany-browser. 

The PhpStorm issue is not fixed because it's actually a bug that also happens in LInux. See https://youtrack.jetbrains.com/issue/IDEA-265390

**Comment by JYInMyHeart** [comment] 2021-05-15 13:59
@onomatopellan I had seen this jetbrains issue. But in x-server such as [GWSL ](https://github.com/Opticos/GWSL-Source)there is no problem to use `find in files`.

**Comment by onomatopellan** [comment] 2021-05-15 14:03
@JYInMyHeart Interesting. Then it could also be a XWayland bug.

**Comment by JYInMyHeart** [comment] 2021-05-15 14:06
Maybe. Now this issue and #188 still prevent me to use wslg.

**Comment by hideyukn88** [comment] 2021-05-15 18:40
@onomatopellan , thanks for verifying the my change, very appreciate. Yes, PnpStrom's "File In Files" issue is not Z order issue, since window is closed immediately.

@Carobit , currently we haven't released the update with this fix, you will need to build system-distro VHD by yourself to try out the fix at this point, but I'm hoping this will be released soon.

**Comment by Carobit** [comment] 2021-05-17 06:15
Thanks for the information. For me too, this issue and the #188 is a blocker for now.. Also sometimes the main menu disappears like the find in file popup, and I noticed some minor gui glitches. Looking forward to have these issues resolved, as wslg is a pretty promising feature.

**Comment by spronovo** [comment] 2021-05-21 21:53
WSLg 1.0.22 was just released externally. You can pick it up by doing the following from an elevated command prompt:

```
wsl --shutdown
wsl --update
```

This contains Hideyuki's fix for the z ordering issue and should address most issues with child window poping behind their parents. I'm going to close this issue. If you are still experiencing issue with some applications, please open new issue with details of the repro so we can track those down. For phpstorm, i've reactivated #96 to track that one.

**Closed by spronovo** 2021-05-21 21:53 UTC
Labels: bug, fixinbound
