### ISSUE TITLE
after installing wslg wsl breaks 

### ISSUE THREAD

**Issue by github348** [microsoft/wslg#31] opened 2021-04-22 06:45 UTC
# Environment

Microsoft Windows [Version 10.0.21359.1]

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Your Distribution version: [On Debian or Ubuntu run `lsb_release -r` in WSL]
Your WSLg version: [Open 'Apps and Features' and check the version of 'Windows Subsystem for Linux GUI app support', e.g: 0.2.3.13]
1.0.1
```

# Steps to reproduce
run wsl --update
try to start a distro 

**WSL logs**: 

* Attach WSLg logs from  `/mnt/wslg`

You can access the wslg logs using explorer at: `\\wsl\<Distro-Name>\mnt\wslg` (eg: `\\wsl\Ubuntu-20.04\mnt\wslg`)

* `puseaudio.log`
* `weston.log`
* `versions.txt`

#  Expected behavior
wsl starts as expected with gui support 

# Actual behavior
wsl does not work at all

**Comment by spronovo** [comment] 2021-04-22 07:31
@github348 Looks like you are still running last week insider build (**Microsoft Windows [Version 10.0.21359.1]**), not the new build that was released earlier today (21364). Can you try updating and see if things works correctly afterward? 

On older build like 21359 WSLg shouldn't be getting pulled at all when doing wsl --update... that command should only be pulling the new 5.10.16 Linux kernel we recently published... which shouldn't have an impact on launching your WSL distro... but before spending too much time on this, i would suggest updating to the latest build, and if things still fail we can dig into what's going on there.

**Comment by github348** [comment] 2021-04-22 08:38
I upgraded to latest insider build and ran wsl --update and it installed wslg now whenever I start wsl I get the error 
The parameter is incorrect.
when i try to install a new distribution from store this error appears 
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80070057
Error: 0x80070057 The parameter is incorrect.

Press any key to continue...
when i uninstall wslg from apps and features and restart windows everything works

**Comment by adrastogi** [comment] 2021-04-22 17:47
This 0x80070057 problem is being tracked and investigated over on the WSL repo via the issue [here](https://github.com/microsoft/WSL/issues/6839).

**Comment by hideyukn88** [comment] 2021-04-22 23:20
@github348 , regarding to "Error: 0x80070057 The parameter is incorrect.", it can be same issue as https://github.com/microsoft/wslg/issues/33. Please provide wsl.etl if further investigation is needed.

**Comment by spronovo** [comment] 2021-04-23 15:08
Closing as a duplicate of #33, we're working on pushing the fix for this in Windows.

**Closed by spronovo** 2021-04-23 15:08 UTC
Labels: bug
